-- Codigo DDL Grupo 4

-- Tabela FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
    FUNCIONARIO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    CARGO VARCHAR2(100),
    SALARIO NUMBER(10,2),
    DATA_ADMISSAO DATE,
    CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (FUNCIONARIO_ID)
);

-- TABELA PROJETOS
CREATE TABLE PROJETOS (
    PROJETO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    ORCAMENTO NUMBER(10,2),
    CONSTRAINT PK_PROJETOS PRIMARY KEY (PROJETO_ID)
);

-- TABELA TAREFAS
CREATE TABLE TAREFAS (
    TAREFA_ID NUMBER NOT NULL,
    PROJETO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    RESPONSAVEL_ID NUMBER,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS VARCHAR2(50),
    CONSTRAINT PK_TAREFAS PRIMARY KEY (TAREFA_ID),
    CONSTRAINT FK_TAREFAS_PROJETO FOREIGN KEY (PROJETO_ID)
        REFERENCES PROJETOS (PROJETO_ID),
    CONSTRAINT FK_TAREFAS_RESPONSAVEL FOREIGN KEY (RESPONSAVEL_ID)
        REFERENCES FUNCIONARIOS (FUNCIONARIO_ID)
);

-- TABELA ALOCACOES_RECURSOS
CREATE TABLE ALOCACOES_RECURSOS (
    ALOCACAO_ID NUMBER NOT NULL,
    PROJETO_ID NUMBER NOT NULL,
    FUNCIONARIO_ID NUMBER NOT NULL,
    HORAS_TRABALHADAS NUMBER(5,2),
    CONSTRAINT PK_ALOCACOES_RECURSOS PRIMARY KEY (ALOCACAO_ID),
    CONSTRAINT FK_ALOCACOES_PROJETO FOREIGN KEY (PROJETO_ID)
        REFERENCES PROJETOS (PROJETO_ID),
    CONSTRAINT FK_ALOCACOES_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID)
        REFERENCES FUNCIONARIOS (FUNCIONARIO_ID)
);

-- Criação de índices para otimizar consultas
CREATE INDEX IDX_TAREFAS_PROJETO_ID ON TAREFAS (PROJETO_ID);
CREATE INDEX IDX_TAREFAS_RESPONSAVEL_ID ON TAREFAS (RESPONSAVEL_ID);
CREATE INDEX IDX_ALOCACOES_PROJETO_ID ON ALOCACOES_RECURSOS (PROJETO_ID);
CREATE INDEX IDX_ALOCACOES_FUNCIONARIO_ID ON ALOCACOES_RECURSOS (FUNCIONARIO_ID);