-- Inserção na tabela FUNCIONARIOS
INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (1, 'João Silva', TO_DATE('1985-04-15', 'YYYY-MM-DD'), 'Desenvolvedor', 5500.00, TO_DATE('2020-01-10', 'YYYY-MM-DD'));

INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (2, 'Maria Oliveira', TO_DATE('1990-07-22', 'YYYY-MM-DD'), 'Analista de Projetos', 6500.00, TO_DATE('2019-05-15', 'YYYY-MM-DD'));

INSERT INTO FUNCIONARIOS (FUNCIONARIO_ID, NOME, DATA_NASCIMENTO, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (3, 'Carlos Santos', TO_DATE('1992-11-02', 'YYYY-MM-DD'), 'Gerente de Projetos', 8500.00, TO_DATE('2018-09-01', 'YYYY-MM-DD'));

-- Inserção na tabela PROJETOS
INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (1, 'Sistema de Gestão', 'Desenvolvimento de um sistema de gestão para empresas.', TO_DATE('2023-01-15', 'YYYY-MM-DD'), TO_DATE('2023-12-31', 'YYYY-MM-DD'), 150000.00);

INSERT INTO PROJETOS (PROJETO_ID, NOME, DESCRICAO, DATA_INICIO, DATA_FIM, ORCAMENTO)
VALUES (2, 'Aplicativo Mobile', 'Criação de um aplicativo para dispositivos móveis.', TO_DATE('2023-06-01', 'YYYY-MM-DD'), TO_DATE('2024-05-31', 'YYYY-MM-DD'), 80000.00);

-- Inserção na tabela TAREFAS
INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (1, 1, 'Análise de Requisitos', 'Levantamento de requisitos com o cliente.', 1, TO_DATE('2023-01-15', 'YYYY-MM-DD'), TO_DATE('2023-02-15', 'YYYY-MM-DD'), 'Concluído');

INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (2, 1, 'Desenvolvimento Backend', 'Implementação da lógica de negócio.', 2, TO_DATE('2023-02-16', 'YYYY-MM-DD'), TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'Em Andamento');

INSERT INTO TAREFAS (TAREFA_ID, PROJETO_ID, NOME, DESCRICAO, RESPONSAVEL_ID, DATA_INICIO, DATA_FIM, STATUS)
VALUES (3, 2, 'Design UI/UX', 'Criação do layout do aplicativo.', 1, TO_DATE('2023-06-01', 'YYYY-MM-DD'), TO_DATE('2023-08-01', 'YYYY-MM-DD'), 'Concluído');

-- Inserção na tabela ALOCACOES_RECURSOS
INSERT INTO ALOCACOES_RECURSOS (ALOCACAO_ID, PROJETO_ID, FUNCIONARIO_ID, HORAS_TRABALHADAS)
VALUES (1, 1, 1, 150.00);

INSERT INTO ALOCACOES_RECURSOS (ALOCACAO_ID, PROJETO_ID, FUNCIONARIO_ID, HORAS_TRABALHADAS)
VALUES (2, 1, 2, 200.00);

INSERT INTO ALOCACOES_RECURSOS (ALOCACAO_ID, PROJETO_ID, FUNCIONARIO_ID, HORAS_TRABALHADAS)
VALUES (3, 2, 1, 100.00);

COMMIT;
